"use client";
import { FormEvent, useMemo, useState } from "react";
import { calculateQuote, MAX_GUESTS, MIN_NIGHTS, money } from "./pricing";

export default function BookingForm() {
  const [state,setState]=useState<"idle"|"sending"|"sent"|"error">("idle");
  const [message,setMessage]=useState("");
  const [arrival,setArrival]=useState(""),[departure,setDeparture]=useState("");
  const [adults,setAdults]=useState(1),[children,setChildren]=useState(0);
  const [boatRental,setBoatRental]=useState(false),[pet,setPet]=useState(false);
  const quote=useMemo(()=>calculateQuote(arrival,departure,adults,children,boatRental,pet?1:0),[arrival,departure,adults,children,boatRental,pet]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("sending");const form=new FormData(event.currentTarget);const response=await fetch("/api/booking-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form.entries()))});const result=await response.json() as {error?:string};if(!response.ok){setMessage(result.error??"Please try again.");setState("error");return;}setState("sent");}
  if(state==="sent")return <div className="success"><span>✓</span><h3>Your request is in.</h3><p>We emailed your quote and sent it to the owners for review. Nothing has been charged. If approved, you’ll receive confirmed dates, the amount due and your choice of payment options.</p><button onClick={()=>setState("idle")}>Request different dates</button></div>;
  return <form className="bookingForm" onSubmit={submit}>
    <div className="two"><label>Arrival<input name="arrival" type="date" value={arrival} onChange={e=>setArrival(e.target.value)} required/></label><label>Departure<input name="departure" type="date" value={departure} onChange={e=>setDeparture(e.target.value)} required/></label></div>
    <div className="two"><label>Adults (13+)<input name="adults" type="number" min="1" max={MAX_GUESTS} value={adults} onChange={e=>setAdults(Number(e.target.value))} required/></label><label>Children (ages 0–12)<input name="children" type="number" min="0" max={MAX_GUESTS-1} value={children} onChange={e=>setChildren(Number(e.target.value))} required/></label></div>
    <label className="check addOn"><input name="boatRental" type="checkbox" value="yes" checked={boatRental} onChange={e=>setBoatRental(e.target.checked)}/><span><strong>Add pontoon / jet-ski rental</strong><small>$100 per day · Kayaks are included at no charge</small></span></label>
    <label className="check addOn"><input name="pets" type="checkbox" value="1" checked={pet} onChange={e=>setPet(e.target.checked)}/><span><strong>Bringing a pet</strong><small>$99 flat pet fee per stay</small></span></label>
    {quote.nights>=MIN_NIGHTS&&quote.guests<=MAX_GUESTS&&<div className="quoteBox"><div><span>Lodging · {quote.nights} nights</span><strong>{money(quote.lodgingCents)}</strong></div>{quote.shoulderNights>0&&<small>{quote.shoulderNights} shoulder-season {quote.shoulderNights===1?"night":"nights"} receive 25% off.</small>}<div><span>Cleaning fee</span><strong>{money(quote.cleaningCents)}</strong></div>{boatRental&&<div><span>Boat rental · {quote.nights} days</span><strong>{money(quote.boatRentalCents)}</strong></div>}{pet&&<div><span>Flat pet fee</span><strong>{money(quote.petCents)}</strong></div>}<div><span>Michigan lodging tax (6%)</span><strong>{money(quote.taxCents)}</strong></div><div className="quoteTotal"><span>Estimated total</span><strong>{money(quote.totalCents)}</strong></div><small>Children ages 0–12 are priced at $25/night. Summer rates are capped at $699/night. Final approval is required.</small></div>}
    <label>Your name<input name="name" autoComplete="name" required/></label><div className="two"><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required/></label></div><label>Tell us about your stay<textarea name="note" rows={4} placeholder="What brings you to Klinger Lake?"/></label>
    <div className="cancellationPolicy"><strong>Flexible 7-day cancellation</strong><p>Email your cancellation request to <a href="mailto:bockal@gmail.com">bockal@gmail.com</a> at least seven full days before check-in for a full refund. Requests received fewer than seven days before check-in are not eligible for a full refund.</p></div>
    <label className="check"><input name="agreement" type="checkbox" value="yes" required/><span>I understand this is a request, not a confirmed reservation, and I have reviewed the cancellation policy.</span></label>{state==="error"&&<p className="formError">{message}</p>}<button className="submit" disabled={state==="sending"}>{state==="sending"?"Sending…":"Request these dates"}</button>
    <p className="fine">Two-night minimum · 12 guests maximum · June–August peak pricing · 25% off other months.</p><div className="paymentOptions" aria-label="Payment options available after approval"><span className="zelleLogo">Zelle<sup>®</sup></span><a className="venmoLogo" href="https://venmo.com/u/KlingerLake68109" target="_blank" rel="noreferrer">Venmo</a></div><p className="paymentCaption">Zelle or Venmo details are provided after your dates are approved.</p>
  </form>;
}
