import AvailabilityCalendar from "./availability-calendar";
import BookingForm from "./booking-form";
import "./listing.css";
import "./instagram.css";

const GOOGLE_LISTING="https://maps.app.goo.gl/Q8psuLeMhAzbFGWGA";
const amenities=[["≋","100 ft private shoreline"],["⚓","Private dock / pier"],["☀","1,021 sq ft lakeside deck"],["◒","Kayaks included"],["↝","Pontoon / jet-ski rental · $100/day"],["⌁","Firepit"],["◉","Lake views"],["⌂","Full kitchen with quartz counters"],["♨","Indoor fireplace"],["⌁","High-speed Wi-Fi"],["▣","Smart TVs"],["❄","Central air conditioning"],["♨","Heating"],["◫","Washer and dryer"],["◇","Water softener and filtration"],["P","On-site parking"],["✓","Smoke and CO alarms"]];
const reviews=[
  {name:"Heather Voit",text:"Paradise in Michigan! Beautiful lake house with a fully equipped kitchen, plenty of space for a big…"},
  {name:"Becky Gash",text:"Clean, organized and spacious! The bathrooms and kitchen were updated and the house had a beautiful…"},
  {name:"Rachel Bock",text:"Great Kitchen and convenient location! very clean with great floors and a huge TV."}
];

export default function Home(){return <main>
  <header className="listingNav"><a className="brand" href="#top">THE VUES</a><nav><a href="#details">About</a><a href="#availability">Availability</a><a href="#reviews">Reviews</a><a href="/owner" className="ownerLink">Owner</a></nav></header>
  <div className="listing" id="top">
    <section className="listingTitle"><div><h1>The Vues at Klinger Lake</h1><p><a href={GOOGLE_LISTING} target="_blank" rel="noreferrer">★ 5.0 on Google</a><span>·</span><u>Sturgis, Michigan</u></p></div><a className="share" href={GOOGLE_LISTING} target="_blank" rel="noreferrer">View on Google ↗</a></section>
    <section className="gallery fivePhotoGallery" aria-label="Property gallery"><img className="galleryMain" src="/property/cottage-from-water.webp" alt="The Vues cottage viewed from Klinger Lake"/><img src="/property/street-arrival.jpg" alt="Street arrival view of The Vues with flower boxes"/><img src="/property/interior-to-lake.jpg" alt="Bright view of Klinger Lake from the cottage"/><img src="/property/interior-great-room.webp" alt="Great room and dining area facing Klinger Lake"/><img src="/property/kitchen.jpg" alt="Bright renovated kitchen at The Vues"/><a className="allPhotos" href="https://my.matterport.com/show/?m=EoSVoDF7wqa" target="_blank" rel="noreferrer">▦ Explore the 3D tour</a></section>
    <div className="contentGrid"><div className="details" id="details"><section className="summary"><h2>Entire lakefront home on Klinger Lake</h2><p>12 guests · 5 bedrooms · 3 bathrooms · private waterfront</p></section><section className="featureList"><article><b>⌂</b><div><h3>A true family lake house</h3><p>A spacious year-round home with generous gathering spaces and room for extended family.</p></div></article><article><b>≋</b><div><h3>Right on the water</h3><p>Private shoreline, dock access, broad lake views and unforgettable sunsets.</p></div></article><article><b>✓</b><div><h3>Request-to-book only</h3><p>Every stay is reviewed personally. Nothing is charged until dates and pricing are approved.</p></div></article></section><section className="description"><h2>About this place</h2><p>Once you arrive at The Vues, the world slows down. The open living and dining area, stone fireplace, wall of lake-facing windows and direct water access make this a place for unhurried mornings and long evenings together.</p><p>Klinger Lake is an all-sports lake known for boating, swimming and fishing. The Vues is offered selectively to guests who will enjoy this family home with the same care.</p></section></div><aside id="request"><div className="bookingCard"><h2>Request your stay</h2><p className="cardNote">Enter dates and guests to send an availability request.</p><BookingForm/></div></aside></div>
    <section className="amenities amenityTour" aria-labelledby="amenities-heading"><div><h2 id="amenities-heading">What this place offers</h2><div className="amenityGrid">{amenities.map(([icon,label])=><div className="amenity" key={label}><span aria-hidden="true">{icon}</span><p>{label}</p></div>)}</div></div><div className="tourCard"><div><p className="eyebrow">See it for yourself</p><h2>Walk through every amenity.</h2><p>Explore the kitchen, gathering spaces, bedrooms and lake views in the interactive 3D tour.</p></div><iframe title="Interactive 3D tour of The Vues" src="https://my.matterport.com/show/?m=EoSVoDF7wqa" allowFullScreen allow="autoplay; fullscreen; web-share; xr-spatial-tracking"/><a href="https://my.matterport.com/show/?m=EoSVoDF7wqa" target="_blank" rel="noreferrer">Open the full 3D tour ↗</a></div></section>
    <section id="availability" className="availabilitySection"><AvailabilityCalendar/></section>
    <section id="reviews" className="reviews"><div className="reviewsHead"><div><p className="googleG">G</p><h2>5.0 · 3 Google reviews</h2><p>Guest stories and photos from Klinger Lake.</p></div><a href={GOOGLE_LISTING} target="_blank" rel="noreferrer">Read the reviews on Google ↗</a></div><div className="reviewRail"><ReviewCard review={reviews[0]}/><ReviewPhoto src="/property/deck-view.jpg" alt="Darker evening lake view shared by Heather" caption="Guest photo shared by Heather"/><ReviewCard review={reviews[1]}/><ReviewPhoto src="/property/review-firepit.png" alt="Couple enjoying a lakeside fire at sunset" caption="Evenings made for the lake"/><ReviewCard review={reviews[2]}/><ReviewPhoto src="/property/review-kayaks.png" alt="Guests kayaking in Klinger Lake" caption="Kayaks are included with every stay"/></div></section>
  </div>
  <footer><div className="brand">THE VUES</div><p>Klinger Lake · Sturgis, Michigan</p><a href="/owner">Owner calendar</a></footer>
</main>}

function ReviewCard({review}:{review:{name:string;text:string}}){return <article className="reviewCard"><span>★★★★★</span><blockquote>“{review.text}”</blockquote><h3>{review.name}</h3><a href={GOOGLE_LISTING} target="_blank" rel="noreferrer">Verified on Google ↗</a></article>}
function ReviewPhoto({src,alt,caption}:{src:string;alt:string;caption:string}){return <figure className="reviewPhoto"><img src={src} alt={alt}/><figcaption>{caption}</figcaption></figure>}

